<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "os_amazon_affiliate"
 *
 * Auto generated by Extension Builder 2016-11-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'OS Amazon Affiliate',
	'description' => 'OS Amazon Affiliate',
	'category' => 'module',
	'author' => 'Oliver Seiffert',
	'author_email' => 'support@oliver-seiffert.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);